FROM node:18

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG EMAIL_REPLY_TO
ARG EMAIL_FROM
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG JWT_SECRET
ARG REDIS_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG PORT=5050

ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV EMAIL_REPLY_TO=$EMAIL_REPLY_TO
ENV EMAIL_FROM=$EMAIL_FROM
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_DATABASE=$DB_DATABASE
ENV JWT_SECRET=$JWT_SECRET
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV PORT=$PORT

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5050

RUN npm run build

CMD [ "npm", "run", "start" ]
